const OPTIONS = [
  { name: "Mobile Phone", value: "mobile-phone" },
  { name: "Laptop", value: "laptop" },
  { name: "Tablet", value: "tablet" },
  { name: "Desktop Computer", value: "desktop-computer" },
  { name: "Monitor", value: "monitor" },
  { name: "Printer", value: "printer" },
  { name: "Scanner", value: "scanner" },
  { name: "Television", value: "television" },
  { name: "Set-Top Box", value: "set-top-box" },
  { name: "Game Console", value: "game-console" },
  { name: "Keyboard", value: "keyboard" },
  { name: "Mouse", value: "mouse" },
  { name: "Router", value: "router" },
  { name: "Modem", value: "modem" },
  { name: "External Hard Drive", value: "external-hard-drive" },
  { name: "CD/DVD Player", value: "cd-dvd-player" },
  { name: "Speakers", value: "speakers" },
  { name: "Earphones / Headphones", value: "headphones" },
  { name: "Power Bank", value: "power-bank" },
  { name: "Charger", value: "charger" },
  { name: "Cables and Wires", value: "cables-wires" },
  { name: "Smartwatch", value: "smartwatch" },
  { name: "Digital Camera", value: "digital-camera" },
  { name: "Camcorder", value: "camcorder" },
  { name: "Microwave Oven", value: "microwave-oven" },
  { name: "Toaster", value: "toaster" },
  { name: "Electric Kettle", value: "electric-kettle" },
  { name: "Hair Dryer", value: "hair-dryer" },
  { name: "Iron", value: "iron" },
  { name: "Refrigerator", value: "refrigerator" },
  { name: "Air Conditioner", value: "air-conditioner" },
  { name: "Washing Machine", value: "washing-machine" },
  { name: "Ceiling Fan", value: "ceiling-fan" },
  { name: "Bulbs / CFLs", value: "bulbs-cfls" },
  { name: "Battery", value: "battery" },
  { name: "Inverter", value: "inverter" },
];

export default OPTIONS;
